# ============================================================
#  estacao.properties ? Configurações da Estação IoT
#
# ============================================================

# ?? Broker MQTT ??????????????????
mqtt.broker.host=192.168.1.100
mqtt.broker.port=1883
mqtt.broker.user=
mqtt.broker.password=

# Tempo máximo aguardando conexão inicial (segundos)
mqtt.connection.timeout=30

# Keep-alive: intervalo de ping para manter a sessão viva (segundos)
mqtt.keepalive=60

# ?? Identidade da Estação ????????????????????????????????????
station.id=estacao_01

# Coordenadas fixas da estação (prédio do CE)
station.lat=-5.207645788981328
station.lon=-37.32216460818565

# ?? Tópicos MQTT ????????????????????????????????????????????
# Tópico de telemetria: {base}/{id}/telemetria
mqtt.topic.base=ambiente/estacao
# Tópico de status (LWT e presença online/offline)
mqtt.topic.status=ambiente/estacao/estacao_01/status

# ?? Publicação ???????????????????????????????????????????????
# Intervalo entre publicações (milissegundos)
mqtt.publish.interval.ms=10000

# QoS: 0=at most once | 1=at least once | 2=exactly once
mqtt.publish.qos=1

# Mensagem retida no broker (último estado sempre disponível)
mqtt.publish.retained=false

# ?? Simulação de Sensores ????????????????????????????????????
# Temperatura (°C)
sensor.temp.base=29.0
sensor.temp.sigma=0.4

# Umidade relativa (%)
sensor.hum.base=71.0
sensor.hum.sigma=0.8

# Pressão atmosférica (hPa)
sensor.pressure.base=1013.25
sensor.pressure.sigma=0.3

# CO2 (ppm)
sensor.co2.base=415.0
sensor.co2.sigma=2.5

# Índice UV (0?11)
sensor.uv.base=5.0
sensor.uv.sigma=0.3

# Semente do gerador aleatório
# 0  = aleatório real (diferente a cada execução)
# >0 = fixo (reproduzível ? use para experimentos)
sensor.random.seed=42