# Rede
mqtt.broker.host=192.168.1.100
mqtt.broker.port=1883
mqtt.broker.user=
mqtt.broker.password=

# Identidade
station.id=estacao_01
station.lat=-5.7901
station.lon=-35.2098

# Simulação
sensor.temp.base=29.0
sensor.temp.sigma=0.4
sensor.hum.base=71.0
sensor.hum.sigma=0.8
sensor.pressure.base=1013.25
sensor.co2.base=415.0
sensor.random.seed=42

# Publicação
mqtt.publish.interval.ms=10000
mqtt.publish.qos=1
mqtt.topic.base=ambiente/estacao