[pytest]
; asyncio_mode = auto permite usar @pytest.mark.asyncio
; sem precisar configurar event_loop manualmente em cada teste
asyncio_mode = auto

testpaths = tests

python_files   = test_*.py
python_classes = Test*
python_functions = test_*